package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import summer.db.entity.Mfloor;
import summer.db.entity.MfloorExample;

public interface MfloorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	long countByExample(MfloorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int deleteByExample(MfloorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int insert(Mfloor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int insertSelective(Mfloor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	List<Mfloor> selectByExample(MfloorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	Mfloor selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int updateByExampleSelective(@Param("record") Mfloor record, @Param("example") MfloorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int updateByExample(@Param("record") Mfloor record, @Param("example") MfloorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int updateByPrimaryKeySelective(Mfloor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	int updateByPrimaryKey(Mfloor record);
}