package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import summer.db.entity.Mvitalset;
import summer.db.entity.MvitalsetExample;

public interface MvitalsetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    long countByExample(MvitalsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int deleteByExample(MvitalsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int deleteByPrimaryKey(Integer managerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int insert(Mvitalset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int insertSelective(Mvitalset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    List<Mvitalset> selectByExample(MvitalsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    Mvitalset selectByPrimaryKey(Integer managerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int updateByExampleSelective(@Param("record") Mvitalset record, @Param("example") MvitalsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int updateByExample(@Param("record") Mvitalset record, @Param("example") MvitalsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int updateByPrimaryKeySelective(Mvitalset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvitalset
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    int updateByPrimaryKey(Mvitalset record);
}