package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import summer.db.entity.Testuser;
import summer.db.entity.TestuserExample;

public interface TestuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    long countByExample(TestuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int deleteByExample(TestuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int insert(Testuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int insertSelective(Testuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    List<Testuser> selectByExample(TestuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    Testuser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int updateByExampleSelective(@Param("record") Testuser record, @Param("example") TestuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int updateByExample(@Param("record") Testuser record, @Param("example") TestuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int updateByPrimaryKeySelective(Testuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    int updateByPrimaryKey(Testuser record);
}