package summer.db.entity;

public class Mfloor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mfloor.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mfloor.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mfloor.id
	 * @return  the value of mfloor.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mfloor.id
	 * @param id  the value for mfloor.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mfloor.name
	 * @return  the value of mfloor.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mfloor.name
	 * @param name  the value for mfloor.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}