package summer.db.entity;

public class Mtag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mtag.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mtag.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mtag.x
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private Integer x;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mtag.y
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private Integer y;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mtag.id
	 * @return  the value of mtag.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mtag.id
	 * @param id  the value for mtag.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mtag.name
	 * @return  the value of mtag.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mtag.name
	 * @param name  the value for mtag.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mtag.x
	 * @return  the value of mtag.x
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public Integer getX() {
		return x;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mtag.x
	 * @param x  the value for mtag.x
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setX(Integer x) {
		this.x = x;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mtag.y
	 * @return  the value of mtag.y
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public Integer getY() {
		return y;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mtag.y
	 * @param y  the value for mtag.y
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setY(Integer y) {
		this.y = y;
	}
}