package summer.db.entity;

import java.util.Date;

public class Muser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column muser.userid
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column muser.password
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column muser.authcode
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String authcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column muser.passW1
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String passw1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column muser.passw2
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String passw2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column muser.lastlogindatetime
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private Date lastlogindatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column muser.rawpassword
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String rawpassword;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column muser.userid
	 * @return  the value of muser.userid
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column muser.userid
	 * @param userid  the value for muser.userid
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column muser.password
	 * @return  the value of muser.password
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column muser.password
	 * @param password  the value for muser.password
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column muser.authcode
	 * @return  the value of muser.authcode
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getAuthcode() {
		return authcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column muser.authcode
	 * @param authcode  the value for muser.authcode
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setAuthcode(String authcode) {
		this.authcode = authcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column muser.passW1
	 * @return  the value of muser.passW1
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getPassw1() {
		return passw1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column muser.passW1
	 * @param passw1  the value for muser.passW1
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setPassw1(String passw1) {
		this.passw1 = passw1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column muser.passw2
	 * @return  the value of muser.passw2
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getPassw2() {
		return passw2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column muser.passw2
	 * @param passw2  the value for muser.passw2
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setPassw2(String passw2) {
		this.passw2 = passw2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column muser.lastlogindatetime
	 * @return  the value of muser.lastlogindatetime
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public Date getLastlogindatetime() {
		return lastlogindatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column muser.lastlogindatetime
	 * @param lastlogindatetime  the value for muser.lastlogindatetime
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setLastlogindatetime(Date lastlogindatetime) {
		this.lastlogindatetime = lastlogindatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column muser.rawpassword
	 * @return  the value of muser.rawpassword
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getRawpassword() {
		return rawpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column muser.rawpassword
	 * @param rawpassword  the value for muser.rawpassword
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setRawpassword(String rawpassword) {
		this.rawpassword = rawpassword;
	}
}