package summer.db.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Mvitalset {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.manager_no
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private Integer managerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.temperature_max
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private BigDecimal temperatureMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.temperature_min
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private BigDecimal temperatureMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.heartrate_max
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private Integer heartrateMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.heartrate_min
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private Integer heartrateMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.delete_flag
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.version
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvitalset.last_update_time
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.manager_no
     *
     * @return the value of mvitalset.manager_no
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public Integer getManagerNo() {
        return managerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.manager_no
     *
     * @param managerNo the value for mvitalset.manager_no
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setManagerNo(Integer managerNo) {
        this.managerNo = managerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.temperature_max
     *
     * @return the value of mvitalset.temperature_max
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public BigDecimal getTemperatureMax() {
        return temperatureMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.temperature_max
     *
     * @param temperatureMax the value for mvitalset.temperature_max
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setTemperatureMax(BigDecimal temperatureMax) {
        this.temperatureMax = temperatureMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.temperature_min
     *
     * @return the value of mvitalset.temperature_min
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public BigDecimal getTemperatureMin() {
        return temperatureMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.temperature_min
     *
     * @param temperatureMin the value for mvitalset.temperature_min
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setTemperatureMin(BigDecimal temperatureMin) {
        this.temperatureMin = temperatureMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.heartrate_max
     *
     * @return the value of mvitalset.heartrate_max
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public Integer getHeartrateMax() {
        return heartrateMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.heartrate_max
     *
     * @param heartrateMax the value for mvitalset.heartrate_max
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setHeartrateMax(Integer heartrateMax) {
        this.heartrateMax = heartrateMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.heartrate_min
     *
     * @return the value of mvitalset.heartrate_min
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public Integer getHeartrateMin() {
        return heartrateMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.heartrate_min
     *
     * @param heartrateMin the value for mvitalset.heartrate_min
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setHeartrateMin(Integer heartrateMin) {
        this.heartrateMin = heartrateMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.delete_flag
     *
     * @return the value of mvitalset.delete_flag
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.delete_flag
     *
     * @param deleteFlag the value for mvitalset.delete_flag
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.version
     *
     * @return the value of mvitalset.version
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.version
     *
     * @param version the value for mvitalset.version
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvitalset.last_update_time
     *
     * @return the value of mvitalset.last_update_time
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvitalset.last_update_time
     *
     * @param lastUpdateTime the value for mvitalset.last_update_time
     *
     * @mbg.generated Thu Aug 31 22:38:01 JST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}