package summer.db.entity;

public class Tgoods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tgoods.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tgoods.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tgoods.remark
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tgoods.idfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String idfloor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tgoods.idtag
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String idtag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tgoods.idcompany
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String idcompany;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tgoods.idcategory
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	private String idcategory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tgoods.id
	 * @return  the value of tgoods.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tgoods.id
	 * @param id  the value for tgoods.id
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tgoods.name
	 * @return  the value of tgoods.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tgoods.name
	 * @param name  the value for tgoods.name
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tgoods.remark
	 * @return  the value of tgoods.remark
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tgoods.remark
	 * @param remark  the value for tgoods.remark
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tgoods.idfloor
	 * @return  the value of tgoods.idfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getIdfloor() {
		return idfloor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tgoods.idfloor
	 * @param idfloor  the value for tgoods.idfloor
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setIdfloor(String idfloor) {
		this.idfloor = idfloor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tgoods.idtag
	 * @return  the value of tgoods.idtag
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getIdtag() {
		return idtag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tgoods.idtag
	 * @param idtag  the value for tgoods.idtag
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setIdtag(String idtag) {
		this.idtag = idtag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tgoods.idcompany
	 * @return  the value of tgoods.idcompany
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getIdcompany() {
		return idcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tgoods.idcompany
	 * @param idcompany  the value for tgoods.idcompany
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setIdcompany(String idcompany) {
		this.idcompany = idcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tgoods.idcategory
	 * @return  the value of tgoods.idcategory
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getIdcategory() {
		return idcategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tgoods.idcategory
	 * @param idcategory  the value for tgoods.idcategory
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setIdcategory(String idcategory) {
		this.idcategory = idcategory;
	}
}