package summer.db.entity;

import java.util.ArrayList;
import java.util.List;

public class TgoodsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public TgoodsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andIdfloorIsNull() {
			addCriterion("idfloor is null");
			return (Criteria) this;
		}

		public Criteria andIdfloorIsNotNull() {
			addCriterion("idfloor is not null");
			return (Criteria) this;
		}

		public Criteria andIdfloorEqualTo(String value) {
			addCriterion("idfloor =", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorNotEqualTo(String value) {
			addCriterion("idfloor <>", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorGreaterThan(String value) {
			addCriterion("idfloor >", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorGreaterThanOrEqualTo(String value) {
			addCriterion("idfloor >=", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorLessThan(String value) {
			addCriterion("idfloor <", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorLessThanOrEqualTo(String value) {
			addCriterion("idfloor <=", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorLike(String value) {
			addCriterion("idfloor like", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorNotLike(String value) {
			addCriterion("idfloor not like", value, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorIn(List<String> values) {
			addCriterion("idfloor in", values, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorNotIn(List<String> values) {
			addCriterion("idfloor not in", values, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorBetween(String value1, String value2) {
			addCriterion("idfloor between", value1, value2, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdfloorNotBetween(String value1, String value2) {
			addCriterion("idfloor not between", value1, value2, "idfloor");
			return (Criteria) this;
		}

		public Criteria andIdtagIsNull() {
			addCriterion("idtag is null");
			return (Criteria) this;
		}

		public Criteria andIdtagIsNotNull() {
			addCriterion("idtag is not null");
			return (Criteria) this;
		}

		public Criteria andIdtagEqualTo(String value) {
			addCriterion("idtag =", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagNotEqualTo(String value) {
			addCriterion("idtag <>", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagGreaterThan(String value) {
			addCriterion("idtag >", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagGreaterThanOrEqualTo(String value) {
			addCriterion("idtag >=", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagLessThan(String value) {
			addCriterion("idtag <", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagLessThanOrEqualTo(String value) {
			addCriterion("idtag <=", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagLike(String value) {
			addCriterion("idtag like", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagNotLike(String value) {
			addCriterion("idtag not like", value, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagIn(List<String> values) {
			addCriterion("idtag in", values, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagNotIn(List<String> values) {
			addCriterion("idtag not in", values, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagBetween(String value1, String value2) {
			addCriterion("idtag between", value1, value2, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdtagNotBetween(String value1, String value2) {
			addCriterion("idtag not between", value1, value2, "idtag");
			return (Criteria) this;
		}

		public Criteria andIdcompanyIsNull() {
			addCriterion("idcompany is null");
			return (Criteria) this;
		}

		public Criteria andIdcompanyIsNotNull() {
			addCriterion("idcompany is not null");
			return (Criteria) this;
		}

		public Criteria andIdcompanyEqualTo(String value) {
			addCriterion("idcompany =", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyNotEqualTo(String value) {
			addCriterion("idcompany <>", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyGreaterThan(String value) {
			addCriterion("idcompany >", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyGreaterThanOrEqualTo(String value) {
			addCriterion("idcompany >=", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyLessThan(String value) {
			addCriterion("idcompany <", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyLessThanOrEqualTo(String value) {
			addCriterion("idcompany <=", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyLike(String value) {
			addCriterion("idcompany like", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyNotLike(String value) {
			addCriterion("idcompany not like", value, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyIn(List<String> values) {
			addCriterion("idcompany in", values, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyNotIn(List<String> values) {
			addCriterion("idcompany not in", values, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyBetween(String value1, String value2) {
			addCriterion("idcompany between", value1, value2, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcompanyNotBetween(String value1, String value2) {
			addCriterion("idcompany not between", value1, value2, "idcompany");
			return (Criteria) this;
		}

		public Criteria andIdcategoryIsNull() {
			addCriterion("idcategory is null");
			return (Criteria) this;
		}

		public Criteria andIdcategoryIsNotNull() {
			addCriterion("idcategory is not null");
			return (Criteria) this;
		}

		public Criteria andIdcategoryEqualTo(String value) {
			addCriterion("idcategory =", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryNotEqualTo(String value) {
			addCriterion("idcategory <>", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryGreaterThan(String value) {
			addCriterion("idcategory >", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryGreaterThanOrEqualTo(String value) {
			addCriterion("idcategory >=", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryLessThan(String value) {
			addCriterion("idcategory <", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryLessThanOrEqualTo(String value) {
			addCriterion("idcategory <=", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryLike(String value) {
			addCriterion("idcategory like", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryNotLike(String value) {
			addCriterion("idcategory not like", value, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryIn(List<String> values) {
			addCriterion("idcategory in", values, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryNotIn(List<String> values) {
			addCriterion("idcategory not in", values, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryBetween(String value1, String value2) {
			addCriterion("idcategory between", value1, value2, "idcategory");
			return (Criteria) this;
		}

		public Criteria andIdcategoryNotBetween(String value1, String value2) {
			addCriterion("idcategory not between", value1, value2, "idcategory");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tgoods
	 * @mbg.generated  Thu Aug 31 22:38:01 JST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tgoods
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 29 23:35:45 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}