package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import summer.db.entity.Mcategory;
import summer.db.entity.McategoryExample;

public interface McategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	long countByExample(McategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int deleteByExample(McategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int insert(Mcategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int insertSelective(Mcategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	List<Mcategory> selectByExample(McategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	Mcategory selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int updateByExampleSelective(@Param("record") Mcategory record, @Param("example") McategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int updateByExample(@Param("record") Mcategory record, @Param("example") McategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int updateByPrimaryKeySelective(Mcategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mcategory
	 * @mbg.generated  Thu Aug 10 22:03:11 JST 2017
	 */
	int updateByPrimaryKey(Mcategory record);
}