package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import summer.db.entity.Mcompany;
import summer.db.entity.McompanyExample;

public interface McompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    long countByExample(McompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int deleteByExample(McompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int insert(Mcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int insertSelective(Mcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    List<Mcompany> selectByExample(McompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    Mcompany selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByExampleSelective(@Param("record") Mcompany record, @Param("example") McompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByExample(@Param("record") Mcompany record, @Param("example") McompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByPrimaryKeySelective(Mcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mcompany
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByPrimaryKey(Mcompany record);
}