package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import summer.db.entity.Mtag;
import summer.db.entity.MtagExample;

public interface MtagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    long countByExample(MtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int deleteByExample(MtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int insert(Mtag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int insertSelective(Mtag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    List<Mtag> selectByExample(MtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    Mtag selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByExampleSelective(@Param("record") Mtag record, @Param("example") MtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByExample(@Param("record") Mtag record, @Param("example") MtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByPrimaryKeySelective(Mtag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtag
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByPrimaryKey(Mtag record);
}