package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import summer.db.entity.Muser;
import summer.db.entity.MuserExample;

public interface MuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	long countByExample(MuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int deleteByExample(MuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int deleteByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int insert(Muser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int insertSelective(Muser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	List<Muser> selectByExample(MuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	Muser selectByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByExampleSelective(@Param("record") Muser record, @Param("example") MuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByExample(@Param("record") Muser record, @Param("example") MuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByPrimaryKeySelective(Muser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table muser
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByPrimaryKey(Muser record);
}