package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import summer.db.entity.CompositeTGoods;
import summer.db.entity.Tgoods;
import summer.db.entity.TgoodsExample;

public interface TgoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    long countByExample(TgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int deleteByExample(TgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int insert(Tgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int insertSelective(Tgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    List<Tgoods> selectByExample(TgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    Tgoods selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByExampleSelective(@Param("record") Tgoods record, @Param("example") TgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByExample(@Param("record") Tgoods record, @Param("example") TgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByPrimaryKeySelective(Tgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tgoods
     *
     * @mbg.generated Thu Aug 10 22:03:11 JST 2017
     */
    int updateByPrimaryKey(Tgoods record);
    
    
    List<CompositeTGoods> getAllGoods(CompositeTGoods condition);
    
}