package summer.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import summer.db.entity.CompositeTGoods;
import summer.db.entity.CompositeTGoodsResult;
import summer.db.entity.Tgoods;
import summer.db.entity.TgoodsExample;

public interface TgoodsMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	long countByExample(TgoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int deleteByExample(TgoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int insert(Tgoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int insertSelective(Tgoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	List<Tgoods> selectByExample(TgoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	Tgoods selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByExampleSelective(@Param("record") Tgoods record, @Param("example") TgoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByExample(@Param("record") Tgoods record, @Param("example") TgoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByPrimaryKeySelective(Tgoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tgoods
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	int updateByPrimaryKey(Tgoods record);
	
	
	// Cac function Them Moi tu day
	List<CompositeTGoodsResult> getAllGoods(CompositeTGoods condition);
	int updateDeleteFlagToTrueByID(String id);
    
}