package summer.db.entity;

import java.util.Date;

public class Testuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.userId
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.passWord
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.auth_code
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    private String authCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.past_w1
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    private String pastW1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.past_w2
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    private String pastW2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.lastlogintime
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    private Date lastlogintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.userId
     *
     * @return the value of testuser.userId
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.userId
     *
     * @param userid the value for testuser.userId
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.passWord
     *
     * @return the value of testuser.passWord
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.passWord
     *
     * @param password the value for testuser.passWord
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.auth_code
     *
     * @return the value of testuser.auth_code
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.auth_code
     *
     * @param authCode the value for testuser.auth_code
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.past_w1
     *
     * @return the value of testuser.past_w1
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public String getPastW1() {
        return pastW1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.past_w1
     *
     * @param pastW1 the value for testuser.past_w1
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public void setPastW1(String pastW1) {
        this.pastW1 = pastW1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.past_w2
     *
     * @return the value of testuser.past_w2
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public String getPastW2() {
        return pastW2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.past_w2
     *
     * @param pastW2 the value for testuser.past_w2
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public void setPastW2(String pastW2) {
        this.pastW2 = pastW2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.lastlogintime
     *
     * @return the value of testuser.lastlogintime
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.lastlogintime
     *
     * @param lastlogintime the value for testuser.lastlogintime
     *
     * @mbg.generated Tue Jul 25 05:56:35 JST 2017
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }
}