package summer.db.entity;

public class Mcategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mcategory.id
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mcategory.name
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mcategory.deleteFlag
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	private Boolean deleteflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mcategory.id
	 * @return  the value of mcategory.id
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mcategory.id
	 * @param id  the value for mcategory.id
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mcategory.name
	 * @return  the value of mcategory.name
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mcategory.name
	 * @param name  the value for mcategory.name
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mcategory.deleteFlag
	 * @return  the value of mcategory.deleteFlag
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public Boolean getDeleteflag() {
		return deleteflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mcategory.deleteFlag
	 * @param deleteflag  the value for mcategory.deleteFlag
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public void setDeleteflag(Boolean deleteflag) {
		this.deleteflag = deleteflag;
	}
}