package summer.db.entity;

public class Mcompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mcompany.id
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mcompany.name
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mcompany.id
	 * @return  the value of mcompany.id
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mcompany.id
	 * @param id  the value for mcompany.id
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mcompany.name
	 * @return  the value of mcompany.name
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mcompany.name
	 * @param name  the value for mcompany.name
	 * @mbg.generated  Sat Aug 12 18:06:44 JST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}